# Makefile for cleaning up LaTeX auxiliary files

CLEAN_FILES = *.aux *.log *.out *.toc *.lof *.lot *.fls *.fdb_latexmk *.synctex.gz *.bbl *.blg *.nav *.snm

.PHONY: clean

clean:
	rm -f $(CLEAN_FILES)